/**
 * Sanpo Google Fit auth proxy.
 *
 * Cloudflare Worker that holds the refresh token (in KV) so the PWA can
 * stay connected to Google Fit indefinitely without GIS's hourly re-auth
 * loop. The PWA only ever sees short-lived access tokens.
 *
 * Endpoints:
 *   POST /exchange   { code, userKey }     → { access_token, expires_in }
 *   POST /refresh    { userKey }           → { access_token, expires_in }
 *   POST /revoke     { userKey }           → 204
 *   GET  /health                            → "ok"
 *
 * Environment:
 *   GOOGLE_CLIENT_ID      Web OAuth client id (same one the PWA uses)
 *   GOOGLE_CLIENT_SECRET  Web OAuth client secret (server-only!)
 *   ALLOWED_ORIGIN        e.g. https://kentaro-source.github.io
 *   FIT_KV                KV namespace binding for refresh tokens
 *
 * Security model: userKey is a per-device random UUID generated by the
 * PWA. Anyone who steals it can read that user's Fit step counts. For a
 * single-user personal app this is acceptable. The refresh token NEVER
 * leaves the worker.
 */

interface Env {
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  ALLOWED_ORIGIN: string;
  FIT_KV: KVNamespace;
}

interface StoredCreds {
  refresh_token: string;
  access_token?: string;
  expires_at?: number; // unix ms
}

interface GoogleTokenResponse {
  access_token: string;
  expires_in: number;
  refresh_token?: string;
  token_type: string;
  scope: string;
  error?: string;
  error_description?: string;
}

const TOKEN_ENDPOINT = 'https://oauth2.googleapis.com/token';
const REVOKE_ENDPOINT = 'https://oauth2.googleapis.com/revoke';

// Treat tokens as expired this many ms before their real expiry, so a
// concurrent Fit fetch doesn't race the cutoff.
const EXPIRY_BUFFER_MS = 60_000;

function corsHeaders(origin: string): Record<string, string> {
  return {
    'Access-Control-Allow-Origin': origin,
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '86400',
  };
}

function jsonResponse(
  body: unknown,
  status: number,
  origin: string,
): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json',
      ...corsHeaders(origin),
    },
  });
}

function bad(msg: string, origin: string, status = 400): Response {
  return jsonResponse({ error: msg }, status, origin);
}

async function readJson<T>(req: Request): Promise<T | null> {
  try {
    return (await req.json()) as T;
  } catch {
    return null;
  }
}

function isValidUserKey(key: unknown): key is string {
  return (
    typeof key === 'string' &&
    /^[0-9a-fA-F-]{30,}$/.test(key) &&
    key.length <= 64
  );
}

async function googleExchange(
  env: Env,
  code: string,
): Promise<GoogleTokenResponse> {
  const params = new URLSearchParams({
    code,
    client_id: env.GOOGLE_CLIENT_ID,
    client_secret: env.GOOGLE_CLIENT_SECRET,
    // For the popup-based code flow used by GIS initCodeClient.
    redirect_uri: 'postmessage',
    grant_type: 'authorization_code',
  });
  const res = await fetch(TOKEN_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params,
  });
  return (await res.json()) as GoogleTokenResponse;
}

async function googleRefresh(
  env: Env,
  refresh_token: string,
): Promise<GoogleTokenResponse> {
  const params = new URLSearchParams({
    client_id: env.GOOGLE_CLIENT_ID,
    client_secret: env.GOOGLE_CLIENT_SECRET,
    refresh_token,
    grant_type: 'refresh_token',
  });
  const res = await fetch(TOKEN_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params,
  });
  return (await res.json()) as GoogleTokenResponse;
}

async function googleRevoke(token: string): Promise<void> {
  try {
    await fetch(`${REVOKE_ENDPOINT}?token=${encodeURIComponent(token)}`, {
      method: 'POST',
    });
  } catch {
    // best effort
  }
}

async function loadCreds(
  env: Env,
  userKey: string,
): Promise<StoredCreds | null> {
  const raw = await env.FIT_KV.get(`creds:${userKey}`);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as StoredCreds;
  } catch {
    return null;
  }
}

async function saveCreds(
  env: Env,
  userKey: string,
  creds: StoredCreds,
): Promise<void> {
  await env.FIT_KV.put(`creds:${userKey}`, JSON.stringify(creds));
}

async function deleteCreds(env: Env, userKey: string): Promise<void> {
  await env.FIT_KV.delete(`creds:${userKey}`);
}

async function handleExchange(req: Request, env: Env, origin: string) {
  const body = await readJson<{ code?: unknown; userKey?: unknown }>(req);
  if (!body) return bad('invalid json', origin);
  const { code, userKey } = body;
  if (typeof code !== 'string' || !code) return bad('code required', origin);
  if (!isValidUserKey(userKey)) return bad('userKey required', origin);

  const tok = await googleExchange(env, code);
  if (tok.error || !tok.access_token) {
    return jsonResponse(
      { error: tok.error ?? 'exchange_failed', detail: tok.error_description },
      400,
      origin,
    );
  }
  if (!tok.refresh_token) {
    // Could happen if user previously consented and Google didn't re-issue
    // refresh token. We need it to keep the session alive.
    return jsonResponse(
      {
        error: 'no_refresh_token',
        hint:
          'Revoke this app at https://myaccount.google.com/permissions and reconnect',
      },
      400,
      origin,
    );
  }

  const expires_at = Date.now() + tok.expires_in * 1000;
  await saveCreds(env, userKey, {
    refresh_token: tok.refresh_token,
    access_token: tok.access_token,
    expires_at,
  });
  return jsonResponse(
    { access_token: tok.access_token, expires_in: tok.expires_in },
    200,
    origin,
  );
}

async function handleRefresh(req: Request, env: Env, origin: string) {
  const body = await readJson<{ userKey?: unknown }>(req);
  if (!body || !isValidUserKey(body.userKey)) {
    return bad('userKey required', origin);
  }
  const userKey = body.userKey;
  const creds = await loadCreds(env, userKey);
  if (!creds) return bad('not_found', origin, 404);

  // If the cached access_token is still fresh, reuse it.
  if (
    creds.access_token &&
    creds.expires_at &&
    creds.expires_at > Date.now() + EXPIRY_BUFFER_MS
  ) {
    return jsonResponse(
      {
        access_token: creds.access_token,
        expires_in: Math.floor((creds.expires_at - Date.now()) / 1000),
      },
      200,
      origin,
    );
  }

  const tok = await googleRefresh(env, creds.refresh_token);
  if (tok.error || !tok.access_token) {
    // Refresh token revoked or expired — drop our copy so the PWA knows
    // to start a new consent flow.
    if (
      tok.error === 'invalid_grant' ||
      tok.error === 'unauthorized_client'
    ) {
      await deleteCreds(env, userKey);
    }
    return jsonResponse(
      { error: tok.error ?? 'refresh_failed', detail: tok.error_description },
      401,
      origin,
    );
  }

  const expires_at = Date.now() + tok.expires_in * 1000;
  await saveCreds(env, userKey, {
    refresh_token: creds.refresh_token,
    access_token: tok.access_token,
    expires_at,
  });
  return jsonResponse(
    { access_token: tok.access_token, expires_in: tok.expires_in },
    200,
    origin,
  );
}

async function handleRevoke(req: Request, env: Env, origin: string) {
  const body = await readJson<{ userKey?: unknown }>(req);
  if (!body || !isValidUserKey(body.userKey)) {
    return bad('userKey required', origin);
  }
  const creds = await loadCreds(env, body.userKey);
  if (creds) {
    await googleRevoke(creds.refresh_token);
    await deleteCreds(env, body.userKey);
  }
  return new Response(null, { status: 204, headers: corsHeaders(origin) });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const reqOrigin = request.headers.get('Origin') ?? '';

    // CORS preflight
    if (request.method === 'OPTIONS') {
      const allowed = matchOrigin(reqOrigin, env.ALLOWED_ORIGIN);
      return new Response(null, {
        status: 204,
        headers: corsHeaders(allowed),
      });
    }

    // Origin enforcement on POST endpoints
    if (request.method === 'POST') {
      const allowed = matchOrigin(reqOrigin, env.ALLOWED_ORIGIN);
      if (!allowed) {
        return new Response('forbidden origin', { status: 403 });
      }
      if (url.pathname === '/exchange') {
        return handleExchange(request, env, allowed);
      }
      if (url.pathname === '/refresh') {
        return handleRefresh(request, env, allowed);
      }
      if (url.pathname === '/revoke') {
        return handleRevoke(request, env, allowed);
      }
    }

    if (request.method === 'GET' && url.pathname === '/health') {
      return new Response('ok', { status: 200 });
    }

    return new Response('not found', { status: 404 });
  },
};

/** ALLOWED_ORIGIN can be comma-separated for dev + prod. */
function matchOrigin(reqOrigin: string, allowed: string): string {
  const list = allowed.split(',').map((s) => s.trim());
  for (const o of list) {
    if (o && reqOrigin === o) return o;
  }
  return '';
}
