// AUTO-GENERATED by scripts/precompute-distances.ts. Do not edit by hand.
// Run: npx tsx scripts/precompute-distances.ts
//
// Empty until the script runs. generateRoute.ts falls back to great-circle
// (or great-circle through waypoints) for any segment not listed here.
export interface SegmentDistance {
  fromCapitalId: string;
  toCapitalId: string;
  km: number;
  source: 'directions' | 'directions+sea' | 'haversine' | 'haversine+waypoints';
}

export const segmentDistances: Record<string, SegmentDistance> = {};
